### ISSUE TITLE
Meta-path Based Heterogeneous Graph Embedding for Music Recommendation

### ISSUE THREAD

**Issue by 1831290651** [Coder-Yu/Yue#2]
你好，打扰下，这篇论文的代码可否发一份《Meta-path Based Heterogeneous Graph Embedding for Music Recommendation》急需帮忙，多谢多谢。

**Comment by jw-zhang-zju** [comment]
你好，这篇论文是已经毕业的同学当时所做的工作，我需要联系一下，如果能够找到的话会尽快给您回复，不好意思。

**Comment by 1831290651** [comment]
好的，谢谢谢谢。

**Comment by Tina217** [comment]
您好，冒昧打扰，请问关于论文《Meta-path Based Heterogeneous Graph Embedding for Music Recommendation》的代码可否发一份，主要是自己复现有难度周期比较久，希望能够复现论文效果进行学习对比，十分感谢，如果您不回复我也十分理解，祝您生活愉快，再次感谢您！
